name: Data_and_Async
description: JSON serializable
version:  1.0.0

environment:
  sdk:  ^3.1.3

dependencies:
  http:  ^1.1.0
  json_annotation: any

dev_dependencies:
  build_runner:  any
  json_serializable: any